Update workflows (#19)
* Rename files
* apply shellcheck
* Improve branch detection on check update

diff --git a/.github/workflows/check-for-update.yml b/.github/workflows/check-for-update.yml
--- a/.github/workflows/check-for-update.yml
+++ b/.github/workflows/check-for-update.yml
@@ -27,11 +27,24 @@ jobs:
 
       - run: python ./_custom_build/auto_update_main.py
         id: check-version
-#        continue-on-error: true
+
+      - name: Abort if branch exists to avoid force push
+        id: abort-pr
+        run: |
+          set -u
+          BRANCH=release-v${{ steps.check-version.outputs.version }}
+          if git fetch origin "$BRANCH:$BRANCH" ; then
+            echo "Aborting to avoid force push" | tee "$GITHUB_SUMMARY"
+            exit 1;
+          else
+            echo "Branch '$BRANCH' can and should be created" >> "$GITHUB_SUMMARY"
+            exit 0;
+          fi
 
       - name: Debug prints
         run: |
           {
+          echo "New branch: $(git branch)"
           echo "# New version: ${{ steps.check-version.outputs.version }} "
           echo "Update required: ${{ steps.check-version.outputs.update_required }}"
           echo "# Status"
@@ -44,12 +57,17 @@ jobs:
           echo '```'
           } >> "$GITHUB_STEP_SUMMARY"
       - name: Create Pull Request
-        if: steps.check-version.outputs.update_required == 'true'
+        if: steps.check-version.outputs.update_required == 'true' && steps.abort-pr.conclusion == 'success'
         uses: peter-evans/create-pull-request@v5.0.2
         with:
           title: New release v${{ steps.check-version.outputs.version }}
           body: |
-            Files `_custom_build/checksums.cfg` and `_custom_build/VERSION_ACTIONLINT.txt` were updated.
+            PR created by workflow `.github/workflows/check-for-update.yaml`
+
+            Files `_custom_build/checksums.cfg` and `_custom_build/VERSION_ACTIONLINT.txt` (and other) were updated.
+
+            - [ ] check if checksums are corrent
+            - [ ] check if url download links are correct
 
             See release: ${{ steps.check-version.outputs.release_url }}
           commit-message: |
